package recycleview.fpt.canhhh.recycleview.activity;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

import java.util.ArrayList;

import jp.wasabeef.recyclerview.adapters.AlphaInAnimationAdapter;
import jp.wasabeef.recyclerview.adapters.SlideInRightAnimationAdapter;
import recycleview.fpt.canhhh.recycleview.R;
import recycleview.fpt.canhhh.recycleview.adapter.MyAdapter;
import recycleview.fpt.canhhh.recycleview.model.Student;

public class MainActivity extends AppCompatActivity {

    private RecyclerView rccV;
    private ArrayList<Student> data;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        setUpView();
    }
    private void setUpView(){
        rccV = (RecyclerView) findViewById(R.id.rvStudent);
        LinearLayoutManager linerLayout =new LinearLayoutManager(MainActivity.this);
        linerLayout.setOrientation(LinearLayoutManager.VERTICAL);
        rccV.setLayoutManager(linerLayout);
        data = new ArrayList<>();
        initdata();
        MyAdapter adapter = new MyAdapter(MainActivity.this,data);
        AlphaInAnimationAdapter alpha = new AlphaInAnimationAdapter(adapter);
        SlideInRightAnimationAdapter slide = new SlideInRightAnimationAdapter(alpha);
        rccV.setAdapter(slide);
    }
    private void initdata(){
        data.add(new Student("hoàng hữu cảnh",18));
        data.add(new Student("hoàng hữu viet",10));
        data.add(new Student("trần trọng kim",14));
        data.add(new Student("trần văn hữu",12));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("hoàng hữu cảnh",18));
        data.add(new Student("hoàng hữu viet",10));
        data.add(new Student("trần trọng kim",14));
        data.add(new Student("trần văn hữu",12));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("hoàng hữu cảnh",18));
        data.add(new Student("hoàng hữu viet",10));
        data.add(new Student("trần trọng kim",14));
        data.add(new Student("trần văn hữu",12));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("hoàng hữu cảnh",18));
        data.add(new Student("hoàng hữu viet",10));
        data.add(new Student("trần trọng kim",14));
        data.add(new Student("trần văn hữu",12));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("hoàng hữu cảnh",18));
        data.add(new Student("hoàng hữu viet",10));
        data.add(new Student("trần trọng kim",14));
        data.add(new Student("trần văn hữu",12));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("hoàng hữu cảnh",18));
        data.add(new Student("hoàng hữu viet",10));
        data.add(new Student("trần trọng kim",14));
        data.add(new Student("trần văn hữu",12));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("hoàng hữu cảnh",18));
        data.add(new Student("hoàng hữu viet",10));
        data.add(new Student("trần trọng kim",14));
        data.add(new Student("trần văn hữu",12));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("hoàng hữu cảnh",18));
        data.add(new Student("hoàng hữu viet",10));
        data.add(new Student("trần trọng kim",14));
        data.add(new Student("trần văn hữu",12));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
        data.add(new Student("bế văn giáp",19));
    }
}
